version: '3'

services:
  database:
    image: mongo:latest
    volumes:
      - ./data/:/data/db

  website:
    image: gabrielalacchi/personal-site:dev
    volumes:
      - ./files/:/app/frontend/www/files
      - /etc/ssl/localhost/:/localhost/
    ports:
      - 8443:443
    environment:
      - MONGO_URL=mongodb://database:27017
      - CERT_FILE=/localhost/localhost.crt
      - KEY_FILE=/localhost/localhost.key
    depends_on:
      - database

  redirect:
    build: ./redirect/
    ports:
      - 8080:80
