version: '3'

services:
  database:
    image: mongo:latest
    volumes:
      - ./data/:/data/db

  website:
    image: gabrielalacchi/personal-site
    volumes:
      - ./files/:/go/src/github.com/gabrielalacchi/personal-site/frontend/www/files
    ports:
      - 443:443
    environment:
      - MONGO_URL=mongodb://database:27017
      - CERT_FILE=/etc/letsencrypt/live/alacchi.com/fullchain.pem
      - KEY_FILE=/etc/letsencrypt/live/alacchi.com/privkey.pem
    depends_on:
      - database

  redirect:
    build: ./redirect/
    ports:
      - 80:80
