version: '3'

services:
  database:
    image: mongo:latest
    volumes:
      - ./data/:/data/db

  website:
    build: .
    volumes:
      - ./files/:/go/src/github.com/gabrielalacchi/personal-site/frontend/www/files
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://database:27017
    depends_on:
      - database